spring:
  ai:
    model:
      chat: openai

    openai:
      # Global OpenAI API Key and base URL using environment variables
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        base-url: ${OPENAI_BASE_URL}
        completions-path: /v1/chat/completions
        api-key: ${OPENAI_API_KEY}
        options:
          timeout: 120s
          model: gpt-5-mini
          temperature: 1

      embedding:
        embeddings-path: /v1/embeddings
        api-key: ${OPENAI_API_KEY}
        options:
          model: text-embedding-3-small

    # Google Gemini Configuration (uncomment to use)
    #    openai:
    #      api-key: ${GOOGLE_API_KEY}
    #      base-url: ${GOOGLE_BASE_URL}
    #
    #      chat:
    #        base-url: ${GOOGLE_BASE_URL}
    #        completions-path: /openai/chat/completions
    #        api-key: ${GOOGLE_API_KEY}
    #        options:
    #          model: models/gemini-2.5-pro
    #          temperature: 0.7



    # DeepSeek Configuration (uncomment to use)
    #    openai:
    #      api-key: ${DEEPSEEK_API_KEY}
    #      base-url: ${DEEPSEEK_BASE_URL}
    #
    #      chat:
    #        base-url: ${DEEPSEEK_BASE_URL}
    #        completions-path: /chat/completions
    #        api-key: ${DEEPSEEK_API_KEY}
    #        options:
    #          model: deepseek-chat
    #          temperature: 0.7