# Milvus Configuration
milvus:
  host: localhost
  port: 19530
  username: 
  password: 

# Spring Configuration
spring:
  application:
    name: ai
  config:
    import:
      - classpath:application-llm.yml
      - classpath:application-mcp.yml

# Logging Configuration
logging:
  level:
    com.enable.ai: INFO
    io.milvus: INFO
